module.exports = [
  {
    "name": "Brown Brothers Tattoo",
    "address": "904 N California Ave, Chicago, IL 60622",
    "city": "Chicago, IL",
    "phone": "(773) 252-9575",
    "hours": "Monday - Saturday: 12PM - 8PM, Sunday: 1PM - 7PM",
    "website": "https://www.brownbrotherstattoo.com/",
    "img": "https://i.imgur.com/wt31dZE.png",
    "artists": [{
      "artistName": "Max Brown",
      "instagramHandle": "@maxwellquesterbrown",
      "rating": 5,
    }],
    "takesWalkIns": true,
  },
  {
    "name": "Allied Tattoo",
    "address": "48 1/2, Grattan Street, Brooklyn, NY 11237",
    "city": "Brooklyn, NY",
    "phone": "(347) 725-4861",
    "hours": "Sunday - Thursday: 12PM - 8PM, Friday - Saturday: 12PM - 10PM",
    "website": "http://www.alliedtattoo.com/",
    "img": "https://i.imgur.com/sNPBXIg.jpg",
    "artists": [{
      "artistName": "Ian Wiedrick",
      "instagramHandle": "@ianwtattoo",
      "rating": 5,
    }],
    "takesWalkIns": true,
  },
  {
    "name": "Atlas Tattoo",
    "address": "4543 N. Albina Ave. Portland, Oregon 97217",
    "city": "Portland, OR",
    "phone": "(503) 281-7499",
    "hours": "12PM - 7PM Daily",
    "website": "http://www.atlastattoo.com/",
    "img": "https://i.imgur.com/tTSInSo.jpg",
    "artists": [{
      "artistName": "Greg Whitehead",
      "instagramHandle": "@greggletron",
      "rating": 5,
    }],
    "takesWalkIns": true,
  },
  {
    "name": "Rose Tattoo Parlour",
    "address": "382 Graham Ave, Brooklyn, NY 11211",
    "city": "Brooklyn, NY",
    "phone": "(347) 529-5064",
    "hours": "12PM - 8PM Daily",
    "website": "https://www.rosetattoonyc.com/",
    "img": "https://i.imgur.com/gqYoZHh.png",
    "artists": [{
      "artistName": "Mark Cross",
      "instagramHandle": "@mark__cross",
      "rating": 5,
    }],
    "takesWalkIns": true,
  },
  {
    "name": "Smith Street Tattoo Parlour",
    "address": "411 Smith St, Brooklyn, NY 11231",
    "city": "Brooklyn, NY",
    "phone": "(718) 643-0463",
    "hours": "11AM - 8PM Tuesday - Sunday, Closed Monday",
    "website": "https://www.sstp.store",
    "img": "https://i.imgur.com/L4kwYYa.jpg",
    "artists": [],
    "takesWalkIns": true,
  },
  {
    "name": "Tattoo Faction",
    "address": "30584 Lorain Rd, North Olmsted, OH 44070",
    "city": "North Olmsted, OH",
    "phone": "(440) 686-1311",
    "hours": "10AM - 11PM Monday - Saturday, 12PM - 6PM Sunday",
    "website": "https://tattoofaction.com/home.html",
    "img": "https://i.imgur.com/dtxpT4k.png",
    "artists": [],
    "takesWalkIns": true,
  },
  {
    "name": "Depot Town Tattoo",
    "address": "33 E Cross St, Ypsilanti, MI 48197",
    "city": "Ypsilanti, MI",
    "phone": "(734) 544-1297",
    "hours": "1PM - 8PM Monday - Saturday, 12PM - 6PM Sunday",
    "website": "https://depottowntattoo.com/home.html",
    "img": "https://i.imgur.com/i2gBcEC.png",
    "artists": [],
    "takesWalkIns": true,
  },
  {
    "name": "Great Lakes Tattoo",
    "address": "1148 W Grand Ave, Chicago, IL 60642",
    "city": "Chicago, IL",
    "phone": "(312) 870-0458",
    "hours": "12PM - 8 PM Daily",
    "website": "https://www.greatlakestattoo.com/",
    "img": "https://i.imgur.com/gazUiue.jpg",
    "artists": [],
    "takesWalkIns": true,
  },
  {
    "name": "Idle Hand Tattoo",
    "address": "575 Haight St, San Francisco, CA 94117",
    "city": "San Francisco, CA",
    "phone": "(415) 552-4353",
    "hours": "12PM - 8 PM Daily",
    "website": "http://www.idlehandsf.com/",
    "img": "https://i.imgur.com/hZP124M.jpg",
    "artists": [],
    "takesWalkIns": true,
  },
]
